In [1]:
import numpy as np
import pandas as pd

credit_df = pd.read_excel("default_of_credit_card_clients.xls")
credit_df

Unnamed: 0         X1   X2         X3        X4   X5     X6     X7  \
0             ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2   
1              1      20000    2          2         1   24      2      2   
2              2     120000    2          2         2   26     -1      2   
3              3      90000    2          2         2   34      0      0   
4              4      50000    2          2         1   37      0      0   
...          ...        ...  ...        ...       ...  ...    ...    ...   
29996      29996     220000    1          3         1   39      0      0   
29997      29997     150000    1          3         2   43     -1     -1   
29998      29998      30000    1          2         2   37      4      3   
29999      29999      80000    1          3         1   41      1     -1   
30000      30000      50000    1          2         1   46      0      0   

          X8     X9  ...        X15        X16        X17       X18       X19  \
0      PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2   
1         -1     -1  ...          0          0          0         0       689   
2          0      0  ...       3272       3455       3261         0      1000   
3          0      0  ...      14331      14948      15549      1518      1500   
4          0      0  ...      28314      28959      29547      2000      2019   
...      ...    ...  ...        ...        ...        ...       ...       ...   
29996      0      0  ...      88004      31237      15980      8500     20000   
29997     -1     -1  ...       8979       5190          0      1837      3526   
29998      2     -1  ...      20878      20582      19357         0         0   
29999      0      0  ...      52774      11855      48944     85900      3409   
30000      0      0  ...      36535      32428      15313      2078      1800   

            X20       X21       X22       X23                           Y  
0      PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
1             0         0         0         0                           1  
2          1000      1000         0      2000                           1  
3          1000      1000      1000      5000                           0  
4          1200      1100      1069      1000                           0  
...         ...       ...       ...       ...                         ...  
29996      5003      3047      5000      1000                           0  
29997      8998       129         0         0                           0  
29998     22000      4200      2000      3100                           1  
29999      1178      1926     52964      1804                           1  
30000      1430      1000      1000      1000                           1  

[30001 rows x 25 columns]

In [2]:
credit_df["X1"]

0        LIMIT_BAL
1            20000
2           120000
3            90000
4            50000
           ...    
29996       220000
29997       150000
29998        30000
29999        80000
30000        50000
Name: X1, Length: 30001, dtype: object

In [3]:
# process features

cred2 = credit_df.iloc[:, 1:-1]
target = credit_df.iloc[:,-1]
target
print(cred2)
cred3 = cred2.iloc[1:] #Remove the feature's names
cred3

              X1   X2         X3        X4   X5     X6     X7     X8     X9  \
0      LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4   
1          20000    2          2         1   24      2      2     -1     -1   
2         120000    2          2         2   26     -1      2      0      0   
3          90000    2          2         2   34      0      0      0      0   
4          50000    2          2         1   37      0      0      0      0   
...          ...  ...        ...       ...  ...    ...    ...    ...    ...   
29996     220000    1          3         1   39      0      0      0      0   
29997     150000    1          3         2   43     -1     -1     -1     -1   
29998      30000    1          2         2   37      4      3      2     -1   
29999      80000    1          3         1   41      1     -1      0      0   
30000      50000    1          2         1   46      0      0      0      0   

         X10  ...        X14        X15        X16 

X1 X2 X3 X4  X5  X6  X7  X8  X9 X10  ...     X14    X15    X16  \
1       20000  2  2  1  24   2   2  -1  -1  -2  ...     689      0      0   
2      120000  2  2  2  26  -1   2   0   0   0  ...    2682   3272   3455   
3       90000  2  2  2  34   0   0   0   0   0  ...   13559  14331  14948   
4       50000  2  2  1  37   0   0   0   0   0  ...   49291  28314  28959   
5       50000  1  2  1  57  -1   0  -1   0   0  ...   35835  20940  19146   
...       ... .. .. ..  ..  ..  ..  ..  ..  ..  ...     ...    ...    ...   
29996  220000  1  3  1  39   0   0   0   0   0  ...  208365  88004  31237   
29997  150000  1  3  2  43  -1  -1  -1  -1   0  ...    3502   8979   5190   
29998   30000  1  2  2  37   4   3   2  -1   0  ...    2758  20878  20582   
29999   80000  1  3  1  41   1  -1   0   0   0  ...   76304  52774  11855   
30000   50000  1  2  1  46   0   0   0   0   0  ...   49764  36535  32428   

         X17    X18    X19    X20   X21    X22   X23  
1          0      0    689      0     0      0     0  
2       3261      0   1000   1000  1000      0  2000  
3      15549   1518   1500   1000  1000   1000  5000  
4      29547   2000   2019   1200  1100   1069  1000  
5      19131   2000  36681  10000  9000    689   679  
...      ...    ...    ...    ...   ...    ...   ...  
29996  15980   8500  20000   5003  3047   5000  1000  
29997      0   1837   3526   8998   129      0     0  
29998  19357      0      0  22000  4200   2000  3100  
29999  48944  85900   3409   1178  1926  52964  1804  
30000  15313   2078   1800   1430  1000   1000  1000  

[30000 rows x 23 columns]

In [4]:
cred3_vals = cred3.values.astype(float)
cred3_vals

array([[2.0000e+04, 2.0000e+00, 2.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [1.2000e+05, 2.0000e+00, 2.0000e+00, ..., 1.0000e+03, 0.0000e+00,
        2.0000e+03],
       [9.0000e+04, 2.0000e+00, 2.0000e+00, ..., 1.0000e+03, 1.0000e+03,
        5.0000e+03],
       ...,
       [3.0000e+04, 1.0000e+00, 2.0000e+00, ..., 4.2000e+03, 2.0000e+03,
        3.1000e+03],
       [8.0000e+04, 1.0000e+00, 3.0000e+00, ..., 1.9260e+03, 5.2964e+04,
        1.8040e+03],
       [5.0000e+04, 1.0000e+00, 2.0000e+00, ..., 1.0000e+03, 1.0000e+03,
        1.0000e+03]])

In [5]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

scaler = StandardScaler()
scaled_data = scaler.fit_transform(cred3)
scaled_data

array([[-1.13672015,  0.81016074,  0.18582826, ..., -0.30806256,
        -0.31413612, -0.29338206],
       [-0.3659805 ,  0.81016074,  0.18582826, ..., -0.24422965,
        -0.31413612, -0.18087821],
       [-0.59720239,  0.81016074,  0.18582826, ..., -0.24422965,
        -0.24868274, -0.01212243],
       ...,
       [-1.05964618, -1.23432296,  0.18582826, ..., -0.03996431,
        -0.18322937, -0.11900109],
       [-0.67427636, -1.23432296,  1.45111372, ..., -0.18512036,
         3.15253642, -0.19190359],
       [-0.90549825, -1.23432296,  0.18582826, ..., -0.24422965,
        -0.24868274, -0.23713013]])

In [6]:
cov_matrix = pd.DataFrame(data=scaled_data).cov()
cov_matrix

0         1         2         3         4         5         6   \
0   1.000033  0.024756 -0.219168 -0.108143  0.144718 -0.271223 -0.296392   
1   0.024756  1.000033  0.014232 -0.031390 -0.090877 -0.057645 -0.070773   
2  -0.219168  0.014232  1.000033 -0.143469  0.175066  0.105368  0.121570   
3  -0.108143 -0.031390 -0.143469  1.000033 -0.414184  0.019918  0.024200   
4   0.144718 -0.090877  0.175066 -0.414184  1.000033 -0.039449 -0.050149   
5  -0.271223 -0.057645  0.105368  0.019918 -0.039449  1.000033  0.672187   
6  -0.296392 -0.070773  0.121570  0.024200 -0.050149  0.672187  1.000033   
7  -0.286132 -0.066098  0.114029  0.032689 -0.053050  0.574264  0.766577   
8  -0.267469 -0.060175  0.108797  0.033123 -0.049723  0.538859  0.662089   
9  -0.249420 -0.055066  0.097523  0.035630 -0.053828  0.509443  0.622801   
10 -0.235203 -0.044009  0.082319  0.034346 -0.048775  0.474569  0.575520   
11  0.285439 -0.033643  0.023582 -0.023473  0.056240  0.187075  0.234894   
12  0.278324 -0.031185  0.018749 -0.021602  0.054285  0.189865  0.235265   
13  0.283245 -0.024564  0.013003 -0.024910  0.053711  0.179791  0.224153   
14  0.293997 -0.021880 -0.000451 -0.023345  0.051355  0.179131  0.222244   
15  0.295572 -0.017006 -0.007567 -0.025394  0.049347  0.180641  0.221356   
16  0.290399 -0.016734 -0.009099 -0.021208  0.047614  0.176986  0.219411   
17  0.195242 -0.000242 -0.037457 -0.005979  0.026148 -0.079271 -0.080703   
18  0.178414 -0.001391 -0.030039 -0.008093  0.021786 -0.070103 -0.058992   
19  0.210174 -0.008597 -0.039944 -0.003541  0.029248 -0.070563 -0.055903   
20  0.203249 -0.002229 -0.038219 -0.012660  0.021380 -0.064007 -0.046860   
21  0.217210 -0.001667 -0.040360 -0.001205  0.022851 -0.058192 -0.037094   
22  0.219603 -0.002766 -0.037201 -0.006641  0.019479 -0.058675 -0.036502   

          7         8         9   ...        13        14        15        16  \
0  -0.286132 -0.267469 -0.249420  ...  0.283245  0.293997  0.295572  0.290399   
1  -0.066098 -0.060175 -0.055066  ... -0.024564 -0.021880 -0.017006 -0.016734   
2   0.114029  0.108797  0.097523  ...  0.013003 -0.000451 -0.007567 -0.009099   
3   0.032689  0.033123  0.035630  ... -0.024910 -0.023345 -0.025394 -0.021208   
4  -0.053050 -0.049723 -0.053828  ...  0.053711  0.051355  0.049347  0.047614   
5   0.574264  0.538859  0.509443  ...  0.179791  0.179131  0.180641  0.176986   
6   0.766577  0.662089  0.622801  ...  0.224153  0.222244  0.221356  0.219411   
7   1.000033  0.777385  0.686797  ...  0.227502  0.227210  0.225153  0.222334   
8   0.777385  1.000033  0.819863  ...  0.244991  0.245925  0.242910  0.239162   
9   0.686797  0.819863  1.000033  ...  0.243343  0.271924  0.269792  0.262518   
10  0.632705  0.716473  0.816927  ...  0.241189  0.266365  0.290903  0.285100   
11  0.208480  0.202819  0.206691  ...  0.892308  0.860301  0.829806  0.802677   
12  0.237302  0.225824  0.226921  ...  0.928357  0.892512  0.859807  0.831621   
13  0.227502  0.244991  0.243343  ...  1.000033  0.924000  0.883939  0.853349   
14  0.227210  0.245925  0.271924  ...  0.924000  1.000033  0.940166  0.900971   
15  0.225153  0.242910  0.269792  ...  0.883939  0.940166  1.000033  0.946228   
16  0.222334  0.239162  0.262518  ...  0.853349  0.900971  0.946228  1.000033   
17  0.001295 -0.009362 -0.006089  ...  0.244343  0.233020  0.217038  0.199972   
18 -0.066796 -0.001944 -0.003191  ...  0.316947  0.207571  0.181253  0.172669   
19 -0.053313 -0.069238  0.009063  ...  0.130016  0.300033  0.252313  0.233778   
20 -0.046068 -0.043463 -0.058301  ...  0.143409  0.130196  0.293128  0.250245   
21 -0.035864 -0.033591 -0.033338  ...  0.179718  0.160438  0.141579  0.307739   
22 -0.035862 -0.026566 -0.023028  ...  0.182332  0.177643  0.164190  0.115498   

          17        18        19        20        21        22  
0   0.195242  0.178414  0.210174  0.203249  0.217210  0.219603  
1  -0.000242 -0.001391 -0.008597 -0.002229 -0.001667 -0.002766  
2  -0.037457 -0.030039 -0.039944 -0.038219 -0

In [7]:
eigvals, eigvecs = np.linalg.eig(cov_matrix)
eigvals

array([6.54330745, 4.09846452, 1.55101233, 1.4723145 , 1.02527213,
       0.95723146, 0.9076182 , 0.88764591, 0.87127841, 0.78295576,
       0.73281262, 0.68284393, 0.57096763, 0.52440738, 0.40365398,
       0.25989565, 0.24913679, 0.18869729, 0.13179069, 0.07015803,
       0.04078596, 0.02322001, 0.02529607])

In [8]:
# kept variance for 6 features
kept_variance = 0
for i in range(0,7):
    kept_variance += eigvals[i]**2
kept_variance /= np.sum(eigvals**2)
kept_variance

0.9420820420005543